language: python
python:
- 3.6
sudo: required
env:
  global:
  - secure: EMb8cXBUkt383f5/570ymoAyF53jitd9Z38bUW27+LaxhLyoElI4rSwrTVNdLRd8BHm/yRVFsE73CJ4GB/QUJa+uWYeFcLLx9IYofgNlQfMMTug6LBhcsDukEBOhI2PpDAN8qzOz27qV6ovfQc8o+raAfUpL2o3OulT/o4T5x19h6bhFRxYGaYEWU2z+XdzAePVVBOoZMCtQh1uY3dUL5oxq5wL+Ow+2bANJz0Y5SNB3CG414XmHuEEP/qh19C8NhUFIYknwctYLRFVWr7/+AgGLKtHkSmCLcWuossOeONLqrsceLxJVKRzHsvFQ/7P22Y1yG/F6cEQmIuG0Jd7ub9nS7yZVZPhrj31zTVDY7M63nys+FlmKBRzOmHMEGIthuxm+XbXKUblf4WtXU3sU35W8vP9jpZjUzxktpmX5A6mzbRSF8zlYA30goT/xh9XgxPiurH+zQkgU4buvgjFdChLFoaaBFkK7n8U7hyrQGo7ia4X+JJsSWarKN2Ni6HZY0MRTPMUTtaVWAKF7mLvlhwcmEj5klH6QtuVd4yttyn1nYFKy1FYJOd7/RTK4ohd++Nu5HjXkTvUCIfMqb1+m9w/2mOscqWcRrqnD5HHq5JVqaBNzv5U7hwh9dFBTuzII7XFnQOp5xXGfxzZUF8X3SM9jyCRYL4pLm7JhheYRZ1A=
  - secure: rWQk3FfQo6Mkz9y2Vz089K+HB++KeatUp6c2qKOMzvg5fvK3Gr4p95NGCd4+wOnTJrRJEhqnBrlGv6EaKlAdy5Wb9PZB3UaEasCe/jfy61vLfap7lQMWXwHSVo66tFG1Ff2ug6dLDX1zMUNjtxx90X4J5fUNBBhI9vyLy1uG/AM2fE+r9VCyt0AKUjOvI+gwUH2mTlaSvIfDXhrcfb7OB4iDtkCSVc7xpC7z+G4UC5bqeuJ7fTAUvYH5Pb4Uc9nUCJ2oYP1fYzcGtmVMcrj8ttjVuJLhrGiRM6hFNQNYexN5B4u7wlCvo3vhudqFtAmWVpXn6mCSksn60Wgo4E5cT7XDlKhpygOqZjughOa3LKuLZyHB88AI6irs2CycDChxewAd6QifJOOHPCzEinxKSPHZKlHUdxHmhNXKvv1kw24wwoCe0gXMD68/fg++ku8kfAu/CHp9myl0JkRnJGWblrjMPr7NStGrz5Yi2CSY0YQZ/jM9DyY1ZqOp9CDBxhNkaXPn+o6CxuOfJZ3KarIiHUZfcdKP7H9s+yppSlrexb2t2Tl2l40h1UmyQZqK65mE/Ld9oQuR5rJcbLYqywQQL0V+TaSRwwsQEHwEpIB8PhNfRujUD4rB+u8w8dQiAYaI12GvD6kbjHFDs481JMh7wp4O4HKP8W0UPrtnFQi93SE=
install:
- nvm install 10
- nvm use 10
- pip install transifex-client
- 'curl https://raw.githubusercontent.com/hasadna/reportit-scripts/master/tools/prepare_github.sh > prepare_github.sh'
- npm install
- npm install -g @angular/cli@7.1.3
script:
- ". extract_i18n.sh"
- tx push --source
- tx pull --mode sourceastranslation -l ar,en,am,ru
deploy:
  skip_cleanup: true
  provider: script
  script: "./travis_deploy.sh"
  on:
    branch: master
